config/routes.rb
Rails.application.routes.draw do
  resources :great_grand_children
  resources :grand_children
  resources :children
  resources :parents
  resources :grand_parents
  resources :great_grand_parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/great_grand_parent.rb
class GreatGrandParent < ApplicationRecord
  has_many :grand_parents

  enum gender: { male: 0, female: 1 }
end

app/controllers/great_grand_parents_controller.rb
class GreatGrandParentsController < ApplicationController
  before_action :set_great_grand_parent, only: %i[ show edit update destroy ]

  # GET /great_grand_parents or /great_grand_parents.json
  def index
    @great_grand_parents = GreatGrandParent.all
  end

  # GET /great_grand_parents/1 or /great_grand_parents/1.json
  def show
  end

  # GET /great_grand_parents/new
  def new
    @great_grand_parent = GreatGrandParent.new
  end

  # GET /great_grand_parents/1/edit
  def edit
  end

  # POST /great_grand_parents or /great_grand_parents.json
  def create
    @great_grand_parent = GreatGrandParent.new(great_grand_parent_params)

    respond_to do |format|
      if @great_grand_parent.save
        format.html { redirect_to great_grand_parent_url(@great_grand_parent), notice: "Great grand parent was successfully created." }
        format.json { render :show, status: :created, location: @great_grand_parent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @great_grand_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /great_grand_parents/1 or /great_grand_parents/1.json
  def update
    respond_to do |format|
      if @great_grand_parent.update(great_grand_parent_params)
        format.html { redirect_to great_grand_parent_url(@great_grand_parent), notice: "Great grand parent was successfully updated." }
        format.json { render :show, status: :ok, location: @great_grand_parent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @great_grand_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /great_grand_parents/1 or /great_grand_parents/1.json
  def destroy
    @great_grand_parent.destroy

    respond_to do |format|
      format.html { redirect_to great_grand_parents_url, notice: "Great grand parent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_great_grand_parent
      @great_grand_parent = GreatGrandParent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def great_grand_parent_params
      params.require(:great_grand_parent).permit(:first_name, :last_name, :gender)
    end
end

app/views/great_grand_parents/_form.html.erb
<%= form_with(model: great_grand_parent) do |form| %>
  <% if great_grand_parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(great_grand_parent.errors.count, "error") %> prohibited this great_grand_parent from being saved:</h2>

      <ul>
        <% great_grand_parent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/great_grand_parents/edit.html.erb
<h1>Editing Great Grand Parent</h1>

<%= render 'form', great_grand_parent: @great_grand_parent %>

<%= link_to 'Show', @great_grand_parent %> |
<%= link_to 'Back', great_grand_parents_path %>

app/views/great_grand_parents/index.html.erb
<p id="notice"><%= notice %></p>

<h2>曽祖父世代</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @great_grand_parents.each do |great_grand_parent| %>
      <tr>
        <td><%= great_grand_parent.id %></td>
        <td><%= great_grand_parent.first_name %></td>
        <td><%= great_grand_parent.last_name %></td>
        <td><%= great_grand_parent.gender %></td>
        <td><%= link_to 'Show', great_grand_parent %></td>
        <td><%= link_to 'Edit', edit_great_grand_parent_path(great_grand_parent) %></td>
        <td><%= link_to 'Destroy', great_grand_parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '祖父世代へ', grand_parents_path %>
<br>
<br>

<%= link_to 'New Great Grand Parent', new_great_grand_parent_path %>

app/views/great_grand_parents/new.html.erb
<h1>New Great Grand Parent</h1>

<%= render 'form', great_grand_parent: @great_grand_parent %>

<%= link_to 'Back', great_grand_parents_path %>

app/views/great_grand_parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @great_grand_parent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @great_grand_parent.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @great_grand_parent.gender %>
</p>

<%= link_to 'Edit', edit_great_grand_parent_path(@great_grand_parent) %> |
<%= link_to 'Back', great_grand_parents_path %>