config/routes.rb
Rails.application.routes.draw do
  resources :great_grand_children
  resources :grand_children
  resources :children
  resources :parents
  resources :grand_parents
  resources :great_grand_parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/grand_parent.rb
class GrandParent < ApplicationRecord
  belongs_to :great_grand_parent
  has_many :parents

  enum gender: { male: 0, female: 1 }
end

app/controllers/grand_parents_controller.rb
class GrandParentsController < ApplicationController
  before_action :set_grand_parent, only: %i[ show edit update destroy ]

  # GET /grand_parents or /grand_parents.json
  def index
    @grand_parents = GrandParent.all
  end

  # GET /grand_parents/1 or /grand_parents/1.json
  def show
  end

  # GET /grand_parents/new
  def new
    @grand_parent = GrandParent.new
  end

  # GET /grand_parents/1/edit
  def edit
  end

  # POST /grand_parents or /grand_parents.json
  def create
    @grand_parent = GrandParent.new(grand_parent_params)

    respond_to do |format|
      if @grand_parent.save
        format.html { redirect_to grand_parent_url(@grand_parent), notice: "Grand parent was successfully created." }
        format.json { render :show, status: :created, location: @grand_parent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grand_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grand_parents/1 or /grand_parents/1.json
  def update
    respond_to do |format|
      if @grand_parent.update(grand_parent_params)
        format.html { redirect_to grand_parent_url(@grand_parent), notice: "Grand parent was successfully updated." }
        format.json { render :show, status: :ok, location: @grand_parent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grand_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grand_parents/1 or /grand_parents/1.json
  def destroy
    @grand_parent.destroy

    respond_to do |format|
      format.html { redirect_to grand_parents_url, notice: "Grand parent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grand_parent
      @grand_parent = GrandParent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grand_parent_params
      params.require(:grand_parent).permit(:first_name, :last_name, :gender, :great_grand_parent_id)
    end
end

app/views/grand_parents/_form.html.erb
<%= form_with(model: grand_parent) do |form| %>
  <% if grand_parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grand_parent.errors.count, "error") %> prohibited this grand_parent from being saved:</h2>

      <ul>
        <% grand_parent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="field">
    <%= form.label :great_grand_parent_id %>
    <%= form.number_field :great_grand_parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grand_parents/edit.html.erb
<h1>Editing Grand Parent</h1>

<%= render 'form', grand_parent: @grand_parent %>

<%= link_to 'Show', @grand_parent %> |
<%= link_to 'Back', grand_parents_path %>

app/views/grand_parents/index.html.erb
<p id="notice"><%= notice %></p>

<h2>祖父世代</h2>
<%= link_to '曾祖父世代へ', great_grand_parents_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Great grand parent ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grand_parents.each do |grand_parent| %>
      <tr>
        <td><%= grand_parent.id %></td>
        <td><%= grand_parent.first_name %></td>
        <td><%= grand_parent.last_name %></td>
        <td><%= grand_parent.gender %></td>
        <td><%= grand_parent.great_grand_parent_id %></td>
        <td><%= link_to 'Show', grand_parent %></td>
        <td><%= link_to 'Edit', edit_grand_parent_path(grand_parent) %></td>
        <td><%= link_to 'Destroy', grand_parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '親世代へ', parents_path %>
<br>
<br>

<%= link_to 'New Grand Parent', new_grand_parent_path %>

app/views/grand_parents/new.html.erb
<h1>New Grand Parent</h1>

<%= render 'form', grand_parent: @grand_parent %>

<%= link_to 'Back', grand_parents_path %>

app/views/grand_parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @grand_parent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @grand_parent.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @grand_parent.gender %>
</p>

<p>
  <strong>Great grand parent:</strong>
  <%= @grand_parent.great_grand_parent_id %>
</p>

<%= link_to 'Edit', edit_grand_parent_path(@grand_parent) %> |
<%= link_to 'Back', grand_parents_path %>