config/routes.rb
Rails.application.routes.draw do
  resources :great_grand_children
  resources :grand_children
  resources :children
  resources :parents
  resources :grand_parents
  resources :great_grand_parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/grand_children_controller.rb
class GrandChildrenController < ApplicationController
  before_action :set_grand_child, only: %i[ show edit update destroy ]

  # GET /grand_children or /grand_children.json
  def index
    @grand_children = GrandChild.all
  end

  # GET /grand_children/1 or /grand_children/1.json
  def show
  end

  # GET /grand_children/new
  def new
    @grand_child = GrandChild.new
  end

  # GET /grand_children/1/edit
  def edit
  end

  # POST /grand_children or /grand_children.json
  def create
    @grand_child = GrandChild.new(grand_child_params)

    respond_to do |format|
      if @grand_child.save
        format.html { redirect_to grand_child_url(@grand_child), notice: "Grand child was successfully created." }
        format.json { render :show, status: :created, location: @grand_child }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grand_child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grand_children/1 or /grand_children/1.json
  def update
    respond_to do |format|
      if @grand_child.update(grand_child_params)
        format.html { redirect_to grand_child_url(@grand_child), notice: "Grand child was successfully updated." }
        format.json { render :show, status: :ok, location: @grand_child }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grand_child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grand_children/1 or /grand_children/1.json
  def destroy
    @grand_child.destroy

    respond_to do |format|
      format.html { redirect_to grand_children_url, notice: "Grand child was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grand_child
      @grand_child = GrandChild.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grand_child_params
      params.require(:grand_child).permit(:first_name, :last_name, :gender, :child_id)
    end
end

app/views/grand_children/_form.html.erb
<%= form_with(model: grand_child) do |form| %>
  <% if grand_child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grand_child.errors.count, "error") %> prohibited this grand_child from being saved:</h2>

      <ul>
        <% grand_child.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="field">
    <%= form.label :child_id %>
    <%= form.number_field :child_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grand_children/edit.html.erb
<h1>Editing Grand Child</h1>

<%= render 'form', grand_child: @grand_child %>

<%= link_to 'Show', @grand_child %> |
<%= link_to 'Back', grand_children_path %>

app/views/grand_children/index.html.erb
<p id="notice"><%= notice %></p>

<h2>孫世代</h2>
<%= link_to '子世代へ', children_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Child ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grand_children.each do |grand_child| %>
      <tr>
        <td><%= grand_child.id %></td>
        <td><%= grand_child.first_name %></td>
        <td><%= grand_child.last_name %></td>
        <td><%= grand_child.gender %></td>
        <td><%= grand_child.child_id %></td>
        <td><%= link_to 'Show', grand_child %></td>
        <td><%= link_to 'Edit', edit_grand_child_path(grand_child) %></td>
        <td><%= link_to 'Destroy', grand_child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '曾孫世代へ', great_grand_children_path %>
<br>
<br>

<%= link_to 'New Grand Child', new_grand_child_path %>

app/views/grand_children/new.html.erb
<h1>New Grand Child</h1>

<%= render 'form', grand_child: @grand_child %>

<%= link_to 'Back', grand_children_path %>

app/views/grand_children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @grand_child.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @grand_child.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @grand_child.gender %>
</p>

<p>
  <strong>Child:</strong>
  <%= @grand_child.child_id %>
</p>

<%= link_to 'Edit', edit_grand_child_path(@grand_child) %> |
<%= link_to 'Back', grand_children_path %>