config/routes.rb
Rails.application.routes.draw do
  resources :great_grand_children
  resources :grand_children
  resources :children
  resources :parents
  resources :grand_parents
  resources :great_grand_parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :grand_parent
  has_many :children

  enum gender: { male: 0, female: 1 }
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: %i[ show edit update destroy ]

  # GET /parents or /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1 or /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents or /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to parent_url(@parent), notice: "Parent was successfully created." }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1 or /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to parent_url(@parent), notice: "Parent was successfully updated." }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1 or /parents/1.json
  def destroy
    @parent.destroy

    respond_to do |format|
      format.html { redirect_to parents_url, notice: "Parent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_params
      params.require(:parent).permit(:first_name, :last_name, :gender, :grand_parent_id)
    end
end

app/views/parents/_form.html.erb
<%= form_with(model: parent) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
        <% parent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="field">
    <%= form.label :grand_parent_id %>
    <%= form.number_field :grand_parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h2>親世代</h2>
<%= link_to '祖父世代へ', grand_parents_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名</th>
      <th>姓</th>
      <th>性別</th>
      <th>親ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.id %></td>
        <td><%= parent.first_name %></td>
        <td><%= parent.last_name %></td>
        <td><%= Parent.human_attribute_name("gender.#{parent.gender}") %></td>
        <td><%= parent.grand_parent_id %></td>
        <td><%= link_to '詳細', parent %></td>
        <td><%= link_to '編集', edit_parent_path(parent) %></td>
        <td><%= link_to '削除', parent, method: :delete, data: { confirm: '削除していいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '子世代へ', children_path %>
<br>
<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @parent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @parent.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @parent.gender %>
</p>

<p>
  <strong>Grand parent:</strong>
  <%= @parent.grand_parent_id %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>